version: '3.3'

services:
    base:
        build:
            args:
                CBF_VERSION: ${CBF_VERSION:-master}
                CONTAINER_NAME: base_container
                FROM_BASE: ${DOCKER_REGISTRY:-}ubuntu:cosmic-20180905
                TZ: "America/New_York"
            cache_from:
                - ${DOCKER_REGISTRY:-}ubuntu:cosmic-20180905
            context: .
            dockerfile: Dockerfile
            labels:
                container.build.time: $CONTAINER_BUILD_TIME
                container.cbf.version: $CBF_VERSION
                container.fingerprint: $CONTAINER_FINGERPRINT
                container.git.refs: $CONTAINER_GIT_REFS
                container.git.commit: $CONTAINER_GIT_COMMIT
                container.git.url: $CONTAINER_GIT_URL
                container.origin: $CONTAINER_ORIGIN
                container.original.name: base_container
        container_name: base
        environment:
            DEBIAN_FRONTEND: noninteractive
            DEBUG_TRACE: ${DEBUG_TRACE:-0}
        image: ${DOCKER_REGISTRY:-}${CONTAINER_OS:-ubuntu/}base_container:${CONTAINER_TAG:-latest}
